[2022-03-16 07:48:16.531,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:18:48.934,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:37.012,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:37.949,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:38.841,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.229,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.589,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.660,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.709,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:40.322,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:01.461,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:01.872,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:02.151,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:02.273,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.024,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.625,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.779,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.066,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.667,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.684,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.689,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.762,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:05.575,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:05.622,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.075,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.192,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.875,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.000,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.270,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.946,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.119,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.179,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.517,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.870,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:09.136,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:58:57.869,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 17:28:39.094,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 17:34:43.381,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 17:41:06.452,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 20:49:19.309,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 20:54:37.632,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:00:48.123,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.020,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.417,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.519,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.477,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.673,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.725,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.924,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.416,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.439,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.763,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.223,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.584,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.755,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.426,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.455,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.504,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:12.456,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:12.837,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.147,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.521,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.860,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:14.164,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:14.955,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:15.890,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:16.343,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:16.630,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:17.064,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:52.579,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:52.990,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.197,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.309,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.644,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:54.527,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.362,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.585,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.607,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.969,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.145,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.375,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.488,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:57.219,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:58.071,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:58.692,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.123,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.467,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.902,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:00.513,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:00.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.541,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.724,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.093,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.120,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.532,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.554,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.684,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.718,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.879,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.121,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.166,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.610,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.625,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.173,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.492,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.046,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.536,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.600,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.842,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.254,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.311,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.430,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.652,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.910,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.012,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.017,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.580,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.626,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.814,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.850,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.295,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.339,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.599,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.824,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.952,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.956,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.019,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.071,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.670,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.774,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.882,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.963,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.093,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.339,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.361,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.545,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.782,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.907,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.065,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.128,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.514,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.679,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.864,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.066,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.165,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.199,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.451,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.496,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.652,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.661,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.712,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.978,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.017,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.074,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.149,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.176,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.234,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.472,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.497,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.841,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.899,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.010,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.068,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.301,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.564,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.665,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.668,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.733,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.788,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.858,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.918,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.958,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.184,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.274,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.469,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.514,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.013,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.063,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.119,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.127,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.375,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.549,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.558,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.599,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.655,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.164,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.215,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.457,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.533,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.655,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.677,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.965,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.985,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.157,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.200,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.428,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.531,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.822,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.036,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.358,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.398,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.866,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 11:09:20.278,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:49.523,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:49.924,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:50.113,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:50.282,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:51.076,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:52.072,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:52.191,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:38.518,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:38.602,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:39.185,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 18:00:24.925,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 18:55:43.195,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 19:34:46.985,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 19:59:16.764,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 20:12:40.042,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 20:13:13.357,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 21:41:02.138,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 21:50:09.758,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:04:49.478,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:28:45.906,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:29:20.587,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:30:21.581,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:31:24.964,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 23:31:45.815,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 23:33:08.706,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:20:08.775,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:13.919,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:14.425,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:15.106,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:15.973,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:16.809,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:17.423,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:17.776,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:18.294,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:18.733,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:19.620,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:19.702,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.484,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.884,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.927,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.992,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:21.214,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:21.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.008,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.039,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.056,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.079,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.369,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:25:42.377,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:30:13.249,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:45:58.570,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:11:02.486,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:18:52.795,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:36:52.085,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:57:48.897,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:01:55.204,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:37:07.532,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:52:36.322,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:02:53.319,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:08:24.525,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:15:41.059,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:35:51.265,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:43:51.737,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-20 14:28:28.784,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:37:48.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:38:41.919,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:41:35.136,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:06.409,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:26.999,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:43.882,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:43:06.714,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:51:57.445,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:53:43.223,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:55:31.788,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:56:01.408,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:23.070,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:39.129,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:56.959,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:58:11.396,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-30 16:09:57.116,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-30 16:52:49.927,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-30 17:17:03.576,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-30 20:33:04.213,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-30 22:29:18.718,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-01 09:41:58.805,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-01 17:15:05.365,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-02 12:59:31.565,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:11.691,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:12.380,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:12.457,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:12.802,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:13.243,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:13.510,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:14.032,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:14.573,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:15.196,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:15.333,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:15.608,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:15.900,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:16.055,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:16.205,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:16.502,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.004,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.061,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.116,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.195,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.289,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:17.924,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.006,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.026,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.171,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.173,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.301,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.495,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.777,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:18.884,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.044,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.056,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.095,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.253,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.547,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.583,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.695,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.767,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.805,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:19.954,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.096,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.321,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.382,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.393,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.527,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.715,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.739,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.777,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:20.905,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.029,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.204,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.444,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.504,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.609,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.665,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.769,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.892,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:21.939,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.049,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.162,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.231,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.232,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.360,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.480,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.494,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.624,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.637,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.672,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.750,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.809,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.885,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:22.951,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.214,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.229,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.295,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.340,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.369,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.391,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.434,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.464,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.498,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.572,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.587,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.640,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.654,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.682,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.737,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:23.857,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.085,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.114,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.209,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.256,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.280,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.342,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.425,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.463,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.509,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.584,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.649,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.711,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.773,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.807,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:24.845,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.030,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.060,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.084,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.150,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.252,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.252,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.295,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.343,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.351,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.516,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.581,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.664,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.713,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.754,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.815,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.885,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.909,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:25.942,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.035,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.049,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.063,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.097,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.159,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.314,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.350,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.452,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.467,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-03 10:41:26.660,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-05 08:18:26.622,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-05-05 08:29:44.415,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-05-18 08:44:43.219,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 08:48:42.955,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 08:49:38.619,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 08:52:35.086,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 08:53:11.944,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 08:59:52.801,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:03:11.601,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:04:02.118,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:04:39.656,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:07:45.821,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:08:33.591,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:23.645,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:23.696,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:24.335,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:25.071,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:25.441,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:26.361,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:27.180,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:28.170,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:29.059,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:29.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:29.618,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:30.008,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:30.216,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:30.701,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:31.266,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:31.990,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:32.184,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:32.346,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:32.424,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:33.325,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:34.238,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:34.349,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:34.699,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:34.819,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:34.925,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:35.208,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:35.493,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:35.641,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:35.743,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:35.857,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:36.282,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:36.307,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:36.545,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:37.121,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:37.362,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:37.464,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:37.712,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:38.278,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:38.291,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:38.355,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:38.913,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:38.962,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:39.681,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:39.873,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:40.375,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:40.613,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:40.673,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.456,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.556,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.573,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.611,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.664,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:41.903,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:42.031,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:42.231,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 09:10:42.257,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 13:41:27.158,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 21:45:04.076,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 21:47:08.718,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-18 21:48:22.697,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 08:43:31.326,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 08:44:59.500,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:13:44.840,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:14:06.828,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:16:15.110,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:18:43.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:25:39.118,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:27:36.418,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:02.489,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:03.211,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:03.891,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:04.431,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:04.537,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:04.547,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:04.990,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:05.420,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:06.334,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:06.607,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:06.682,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:07.356,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:07.965,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:08.454,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:08.479,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:08.492,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:08.605,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:08.798,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:09.191,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:09.256,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:09.595,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:09.652,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:10.002,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:10.328,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:10.387,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:10.460,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 09:31:10.832,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:32.641,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:33.152,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:33.620,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:33.899,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:33.939,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:34.126,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:34.465,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:34.760,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:34.804,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:35.247,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:35.533,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:35.553,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:35.905,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:36.134,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:36.853,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:04:36.923,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:17.383,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:17.725,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:18.258,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:18.354,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:18.688,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:19.158,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:19.687,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:19.884,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.082,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.116,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.191,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.428,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.549,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.928,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.953,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:20.992,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.269,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.407,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.716,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.718,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.742,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.752,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.796,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.938,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:21.964,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.010,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.129,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.265,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.286,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.610,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.683,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.860,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:22.898,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.059,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.229,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.289,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.371,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.382,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.646,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.970,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:23.975,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.045,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.172,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.479,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.629,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.764,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.856,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:24.903,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.047,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.183,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.529,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.550,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.621,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.837,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:25.987,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 10:20:26.045,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:28.235,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:28.657,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:28.840,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:29.535,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:30.018,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:30.354,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:31.171,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:31.996,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:32.591,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:32.621,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:33.354,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:33.488,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:34.377,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:34.574,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:35.020,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:35.464,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:35.469,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:35.768,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:36.290,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:36.560,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:37.097,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:37.427,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:37.737,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:37.833,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:37.952,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:38.270,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:38.497,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:39.006,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:39.217,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:39.381,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:39.455,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:40.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:40.384,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:40.597,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:40.677,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:40.920,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.332,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.500,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.538,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.886,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:41.959,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:42.051,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:42.152,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:42.762,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:42.875,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:42.922,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:43.482,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:43.682,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:43.722,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:43.801,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.019,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.029,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.403,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.615,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.729,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.729,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.897,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:44.942,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.169,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.360,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.643,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.660,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.902,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.911,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:45.919,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.086,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.502,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.540,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.661,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.844,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.957,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:46.967,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.024,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.381,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.448,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.533,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.579,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.806,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:47.870,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.053,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.379,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.474,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.771,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-05-20 12:00:48.790,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
