[2022-03-16 07:48:16.531,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:18:48.934,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:37.012,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:37.949,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:38.841,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.229,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.589,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.660,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:39.709,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 13:19:40.322,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:01.461,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:01.872,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:02.151,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:02.273,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.024,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.625,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:03.779,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.066,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.667,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.684,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.689,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:04.762,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:05.575,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:05.622,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.075,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.192,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:06.875,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.000,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.270,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:07.946,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.119,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.179,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.517,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:08.870,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:16:09.136,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 16:58:57.869,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Connection refused
[2022-04-16 17:28:39.094,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 17:34:43.381,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 17:41:06.452,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 20:49:19.309,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 20:54:37.632,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:00:48.123,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.020,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.417,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:57.519,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.477,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.673,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.725,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:58.924,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.416,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.439,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:02:59.763,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.223,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.584,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:00.755,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.426,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.455,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-16 21:03:01.504,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:12.456,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:12.837,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.147,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.521,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:13.860,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:14.164,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:14.955,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:15.890,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:16.343,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:16.630,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 09:18:17.064,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:52.579,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:52.990,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.197,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.309,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:53.644,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:54.527,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.362,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.585,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.607,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:55.969,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.145,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.375,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:56.488,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:57.219,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:58.071,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:58.692,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.123,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.467,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:29:59.902,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:00.513,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:00.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.541,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:01.724,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.093,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.120,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.532,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.554,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.684,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.718,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:02.879,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.121,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.166,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.610,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:03.625,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.173,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.492,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:04.676,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.046,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.536,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.600,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:05.842,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.254,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.311,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.430,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.652,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:06.910,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.012,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.017,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.580,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.626,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.814,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:07.850,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.295,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.339,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.599,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.824,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.952,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:08.956,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.019,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.071,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.670,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.774,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.882,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:09.963,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.093,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.103,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.279,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.339,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.361,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.545,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.782,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:10.907,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.065,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.128,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.514,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.679,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:11.864,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.066,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.165,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.199,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.451,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.496,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.652,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.661,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.712,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:12.978,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.017,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.074,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.149,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.176,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.234,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.472,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.497,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.841,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:13.899,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.010,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.068,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.301,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.564,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.665,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.668,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.733,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.788,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.858,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.918,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:14.958,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.184,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.274,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.469,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:15.514,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.013,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.063,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.119,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.127,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.375,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.549,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.558,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.599,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:16.655,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.164,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.215,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.457,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.533,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.655,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.677,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.965,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:17.985,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.157,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.200,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.428,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.531,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:18.822,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.036,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.358,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.398,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 10:30:19.866,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 11:09:20.278,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:49.523,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:49.924,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:50.113,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:50.282,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:51.076,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:52.072,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:34:52.191,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:38.518,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:38.602,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 17:50:39.185,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 18:00:24.925,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 18:55:43.195,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 19:34:46.985,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 19:59:16.764,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 20:12:40.042,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 20:13:13.357,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 21:41:02.138,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 21:50:09.758,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:04:49.478,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:28:45.906,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:29:20.587,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:30:21.581,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 22:31:24.964,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 23:31:45.815,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-17 23:33:08.706,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:20:08.775,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:13.919,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:14.425,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:15.106,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:15.973,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:16.809,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:17.423,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:17.776,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:18.294,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:18.733,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:19.620,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:19.702,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.484,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.884,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.927,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:20.992,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:21.214,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:21.344,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.008,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.039,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.056,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.079,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:22:22.369,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:25:42.377,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:30:13.249,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-18 18:45:58.570,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:11:02.486,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:18:52.795,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:36:52.085,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 16:57:48.897,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:01:55.204,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:37:07.532,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 17:52:36.322,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:02:53.319,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:08:24.525,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:15:41.059,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:35:51.265,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-19 18:43:51.737,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-20 14:28:28.784,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:37:48.264,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:38:41.919,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:41:35.136,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:06.409,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:26.999,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:42:43.882,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:43:06.714,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:51:57.445,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:53:43.223,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:55:31.788,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:56:01.408,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:23.070,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:39.129,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:57:56.959,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
[2022-04-24 18:58:11.396,Pyro4.core,ERROR] cannot connect to ('127.0.1.1', 32000): [Errno 111] Conexão recusada
